// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v1.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  java.lang.String getApi();
  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  com.google.protobuf.ByteString
      getApiBytes();

  /**
   * <pre>
   * Task entity to add
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  boolean hasToDo();
  /**
   * <pre>
   * Task entity to add
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  com.alterra.deoxys.stub.ToDo getToDo();
  /**
   * <pre>
   * Task entity to add
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  com.alterra.deoxys.stub.ToDoOrBuilder getToDoOrBuilder();
}
