// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

public interface ReadAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v1.ReadAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  java.lang.String getApi();
  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  com.google.protobuf.ByteString
      getApiBytes();

  /**
   * <pre>
   * List of all todo tasks
   * </pre>
   *
   * <code>repeated .v1.ToDo toDos = 2;</code>
   */
  java.util.List<com.alterra.deoxys.stub.ToDo> 
      getToDosList();
  /**
   * <pre>
   * List of all todo tasks
   * </pre>
   *
   * <code>repeated .v1.ToDo toDos = 2;</code>
   */
  com.alterra.deoxys.stub.ToDo getToDos(int index);
  /**
   * <pre>
   * List of all todo tasks
   * </pre>
   *
   * <code>repeated .v1.ToDo toDos = 2;</code>
   */
  int getToDosCount();
  /**
   * <pre>
   * List of all todo tasks
   * </pre>
   *
   * <code>repeated .v1.ToDo toDos = 2;</code>
   */
  java.util.List<? extends com.alterra.deoxys.stub.ToDoOrBuilder> 
      getToDosOrBuilderList();
  /**
   * <pre>
   * List of all todo tasks
   * </pre>
   *
   * <code>repeated .v1.ToDo toDos = 2;</code>
   */
  com.alterra.deoxys.stub.ToDoOrBuilder getToDosOrBuilder(
      int index);
}
