// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

public final class TodoServiceProto {
  private TodoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ToDo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ToDo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ReadAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ReadAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_ReadAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_ReadAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022todo-service.proto\022\002v1\032\037google/protobu" +
      "f/timestamp.proto\"d\n\004ToDo\022\n\n\002id\030\001 \001(\003\022\r\n" +
      "\005title\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022,\n\010rem" +
      "inder\030\004 \001(\0132\032.google.protobuf.Timestamp\"" +
      "4\n\rCreateRequest\022\013\n\003api\030\001 \001(\t\022\026\n\004toDo\030\002 " +
      "\001(\0132\010.v1.ToDo\")\n\016CreateResponse\022\013\n\003api\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\003\"&\n\013ReadRequest\022\013\n\003api\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\003\"3\n\014ReadResponse\022\013\n\003api\030" +
      "\001 \001(\t\022\026\n\004toDo\030\002 \001(\0132\010.v1.ToDo\"4\n\rUpdateR" +
      "equest\022\013\n\003api\030\001 \001(\t\022\026\n\004toDo\030\002 \001(\0132\010.v1.T" +
      "oDo\".\n\016UpdateResponse\022\013\n\003api\030\001 \001(\t\022\017\n\007up" +
      "dated\030\002 \001(\003\"(\n\rDeleteRequest\022\013\n\003api\030\001 \001(" +
      "\t\022\n\n\002id\030\002 \001(\003\".\n\016DeleteResponse\022\013\n\003api\030\001" +
      " \001(\t\022\017\n\007deleted\030\002 \001(\003\"\035\n\016ReadAllRequest\022" +
      "\013\n\003api\030\001 \001(\t\"7\n\017ReadAllResponse\022\013\n\003api\030\001" +
      " \001(\t\022\027\n\005toDos\030\002 \003(\0132\010.v1.ToDo2\377\001\n\013ToDoSe" +
      "rvice\022/\n\006Create\022\021.v1.CreateRequest\032\022.v1." +
      "CreateResponse\022)\n\004Read\022\017.v1.ReadRequest\032" +
      "\020.v1.ReadResponse\022/\n\006Update\022\021.v1.UpdateR" +
      "equest\032\022.v1.UpdateResponse\022/\n\006Delete\022\021.v" +
      "1.DeleteRequest\032\022.v1.DeleteResponse\0222\n\007R" +
      "eadAll\022\022.v1.ReadAllRequest\032\023.v1.ReadAllR" +
      "esponseB2\n\027com.alterra.deoxys.stubB\020Todo" +
      "ServiceProtoP\001\242\002\002SEb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_v1_ToDo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_ToDo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ToDo_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Reminder", });
    internal_static_v1_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v1_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_CreateRequest_descriptor,
        new java.lang.String[] { "Api", "ToDo", });
    internal_static_v1_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_v1_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_CreateResponse_descriptor,
        new java.lang.String[] { "Api", "Id", });
    internal_static_v1_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_v1_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ReadRequest_descriptor,
        new java.lang.String[] { "Api", "Id", });
    internal_static_v1_ReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_v1_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ReadResponse_descriptor,
        new java.lang.String[] { "Api", "ToDo", });
    internal_static_v1_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_v1_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_UpdateRequest_descriptor,
        new java.lang.String[] { "Api", "ToDo", });
    internal_static_v1_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_v1_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_UpdateResponse_descriptor,
        new java.lang.String[] { "Api", "Updated", });
    internal_static_v1_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_v1_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_DeleteRequest_descriptor,
        new java.lang.String[] { "Api", "Id", });
    internal_static_v1_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_v1_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_DeleteResponse_descriptor,
        new java.lang.String[] { "Api", "Deleted", });
    internal_static_v1_ReadAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_v1_ReadAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ReadAllRequest_descriptor,
        new java.lang.String[] { "Api", });
    internal_static_v1_ReadAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_v1_ReadAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_ReadAllResponse_descriptor,
        new java.lang.String[] { "Api", "ToDos", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
