// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

/**
 * <pre>
 * Taks we have to do
 * </pre>
 *
 * Protobuf type {@code v1.ToDo}
 */
public  final class ToDo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v1.ToDo)
    ToDoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ToDo.newBuilder() to construct.
  private ToDo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ToDo() {
    id_ = 0L;
    title_ = "";
    description_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ToDo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (reminder_ != null) {
              subBuilder = reminder_.toBuilder();
            }
            reminder_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reminder_);
              reminder_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_ToDo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_ToDo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alterra.deoxys.stub.ToDo.class, com.alterra.deoxys.stub.ToDo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   * Unique integer identifier of the todo task
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <pre>
   * Title of the task
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Title of the task
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   * Detail description of the todo task
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Detail description of the todo task
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMINDER_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp reminder_;
  /**
   * <pre>
   * Date and time to remind the todo task
   * </pre>
   *
   * <code>.google.protobuf.Timestamp reminder = 4;</code>
   */
  public boolean hasReminder() {
    return reminder_ != null;
  }
  /**
   * <pre>
   * Date and time to remind the todo task
   * </pre>
   *
   * <code>.google.protobuf.Timestamp reminder = 4;</code>
   */
  public com.google.protobuf.Timestamp getReminder() {
    return reminder_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : reminder_;
  }
  /**
   * <pre>
   * Date and time to remind the todo task
   * </pre>
   *
   * <code>.google.protobuf.Timestamp reminder = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getReminderOrBuilder() {
    return getReminder();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (reminder_ != null) {
      output.writeMessage(4, getReminder());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (reminder_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getReminder());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alterra.deoxys.stub.ToDo)) {
      return super.equals(obj);
    }
    com.alterra.deoxys.stub.ToDo other = (com.alterra.deoxys.stub.ToDo) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && (hasReminder() == other.hasReminder());
    if (hasReminder()) {
      result = result && getReminder()
          .equals(other.getReminder());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (hasReminder()) {
      hash = (37 * hash) + REMINDER_FIELD_NUMBER;
      hash = (53 * hash) + getReminder().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alterra.deoxys.stub.ToDo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.ToDo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.ToDo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.ToDo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alterra.deoxys.stub.ToDo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Taks we have to do
   * </pre>
   *
   * Protobuf type {@code v1.ToDo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v1.ToDo)
      com.alterra.deoxys.stub.ToDoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_ToDo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_ToDo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alterra.deoxys.stub.ToDo.class, com.alterra.deoxys.stub.ToDo.Builder.class);
    }

    // Construct using com.alterra.deoxys.stub.ToDo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      title_ = "";

      description_ = "";

      if (reminderBuilder_ == null) {
        reminder_ = null;
      } else {
        reminder_ = null;
        reminderBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_ToDo_descriptor;
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.ToDo getDefaultInstanceForType() {
      return com.alterra.deoxys.stub.ToDo.getDefaultInstance();
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.ToDo build() {
      com.alterra.deoxys.stub.ToDo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.ToDo buildPartial() {
      com.alterra.deoxys.stub.ToDo result = new com.alterra.deoxys.stub.ToDo(this);
      result.id_ = id_;
      result.title_ = title_;
      result.description_ = description_;
      if (reminderBuilder_ == null) {
        result.reminder_ = reminder_;
      } else {
        result.reminder_ = reminderBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alterra.deoxys.stub.ToDo) {
        return mergeFrom((com.alterra.deoxys.stub.ToDo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alterra.deoxys.stub.ToDo other) {
      if (other == com.alterra.deoxys.stub.ToDo.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.hasReminder()) {
        mergeReminder(other.getReminder());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alterra.deoxys.stub.ToDo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alterra.deoxys.stub.ToDo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     * Unique integer identifier of the todo task
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * Unique integer identifier of the todo task
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique integer identifier of the todo task
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * Title of the task
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Title of the task
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Title of the task
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Title of the task
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Title of the task
     * </pre>
     *
     * <code>string title = 2;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Detail description of the todo task
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Detail description of the todo task
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Detail description of the todo task
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Detail description of the todo task
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Detail description of the todo task
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp reminder_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> reminderBuilder_;
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public boolean hasReminder() {
      return reminderBuilder_ != null || reminder_ != null;
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public com.google.protobuf.Timestamp getReminder() {
      if (reminderBuilder_ == null) {
        return reminder_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : reminder_;
      } else {
        return reminderBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public Builder setReminder(com.google.protobuf.Timestamp value) {
      if (reminderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reminder_ = value;
        onChanged();
      } else {
        reminderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public Builder setReminder(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (reminderBuilder_ == null) {
        reminder_ = builderForValue.build();
        onChanged();
      } else {
        reminderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public Builder mergeReminder(com.google.protobuf.Timestamp value) {
      if (reminderBuilder_ == null) {
        if (reminder_ != null) {
          reminder_ =
            com.google.protobuf.Timestamp.newBuilder(reminder_).mergeFrom(value).buildPartial();
        } else {
          reminder_ = value;
        }
        onChanged();
      } else {
        reminderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public Builder clearReminder() {
      if (reminderBuilder_ == null) {
        reminder_ = null;
        onChanged();
      } else {
        reminder_ = null;
        reminderBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getReminderBuilder() {
      
      onChanged();
      return getReminderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getReminderOrBuilder() {
      if (reminderBuilder_ != null) {
        return reminderBuilder_.getMessageOrBuilder();
      } else {
        return reminder_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : reminder_;
      }
    }
    /**
     * <pre>
     * Date and time to remind the todo task
     * </pre>
     *
     * <code>.google.protobuf.Timestamp reminder = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getReminderFieldBuilder() {
      if (reminderBuilder_ == null) {
        reminderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getReminder(),
                getParentForChildren(),
                isClean());
        reminder_ = null;
      }
      return reminderBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v1.ToDo)
  }

  // @@protoc_insertion_point(class_scope:v1.ToDo)
  private static final com.alterra.deoxys.stub.ToDo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alterra.deoxys.stub.ToDo();
  }

  public static com.alterra.deoxys.stub.ToDo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ToDo>
      PARSER = new com.google.protobuf.AbstractParser<ToDo>() {
    @java.lang.Override
    public ToDo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ToDo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ToDo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ToDo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alterra.deoxys.stub.ToDo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

