// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v1.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  java.lang.String getApi();
  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  com.google.protobuf.ByteString
      getApiBytes();

  /**
   * <pre>
   * Contains number of entities have beed updated
   * Equals 1 in case of succesfull update
   * </pre>
   *
   * <code>int64 updated = 2;</code>
   */
  long getUpdated();
}
