// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo-service.proto

package com.alterra.deoxys.stub;

/**
 * <pre>
 * Request data to update todo task
 * </pre>
 *
 * Protobuf type {@code v1.UpdateRequest}
 */
public  final class UpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v1.UpdateRequest)
    UpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateRequest.newBuilder() to construct.
  private UpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateRequest() {
    api_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            api_ = s;
            break;
          }
          case 18: {
            com.alterra.deoxys.stub.ToDo.Builder subBuilder = null;
            if (toDo_ != null) {
              subBuilder = toDo_.toBuilder();
            }
            toDo_ = input.readMessage(com.alterra.deoxys.stub.ToDo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(toDo_);
              toDo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_UpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_UpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alterra.deoxys.stub.UpdateRequest.class, com.alterra.deoxys.stub.UpdateRequest.Builder.class);
  }

  public static final int API_FIELD_NUMBER = 1;
  private volatile java.lang.Object api_;
  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  public java.lang.String getApi() {
    java.lang.Object ref = api_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      api_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * API versioning: it is my best practice to specify version explicitly
   * </pre>
   *
   * <code>string api = 1;</code>
   */
  public com.google.protobuf.ByteString
      getApiBytes() {
    java.lang.Object ref = api_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      api_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TODO_FIELD_NUMBER = 2;
  private com.alterra.deoxys.stub.ToDo toDo_;
  /**
   * <pre>
   * Task entity to update
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  public boolean hasToDo() {
    return toDo_ != null;
  }
  /**
   * <pre>
   * Task entity to update
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  public com.alterra.deoxys.stub.ToDo getToDo() {
    return toDo_ == null ? com.alterra.deoxys.stub.ToDo.getDefaultInstance() : toDo_;
  }
  /**
   * <pre>
   * Task entity to update
   * </pre>
   *
   * <code>.v1.ToDo toDo = 2;</code>
   */
  public com.alterra.deoxys.stub.ToDoOrBuilder getToDoOrBuilder() {
    return getToDo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getApiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, api_);
    }
    if (toDo_ != null) {
      output.writeMessage(2, getToDo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getApiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, api_);
    }
    if (toDo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getToDo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alterra.deoxys.stub.UpdateRequest)) {
      return super.equals(obj);
    }
    com.alterra.deoxys.stub.UpdateRequest other = (com.alterra.deoxys.stub.UpdateRequest) obj;

    boolean result = true;
    result = result && getApi()
        .equals(other.getApi());
    result = result && (hasToDo() == other.hasToDo());
    if (hasToDo()) {
      result = result && getToDo()
          .equals(other.getToDo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + API_FIELD_NUMBER;
    hash = (53 * hash) + getApi().hashCode();
    if (hasToDo()) {
      hash = (37 * hash) + TODO_FIELD_NUMBER;
      hash = (53 * hash) + getToDo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alterra.deoxys.stub.UpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alterra.deoxys.stub.UpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request data to update todo task
   * </pre>
   *
   * Protobuf type {@code v1.UpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v1.UpdateRequest)
      com.alterra.deoxys.stub.UpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_UpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_UpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alterra.deoxys.stub.UpdateRequest.class, com.alterra.deoxys.stub.UpdateRequest.Builder.class);
    }

    // Construct using com.alterra.deoxys.stub.UpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      api_ = "";

      if (toDoBuilder_ == null) {
        toDo_ = null;
      } else {
        toDo_ = null;
        toDoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alterra.deoxys.stub.TodoServiceProto.internal_static_v1_UpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.UpdateRequest getDefaultInstanceForType() {
      return com.alterra.deoxys.stub.UpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.UpdateRequest build() {
      com.alterra.deoxys.stub.UpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alterra.deoxys.stub.UpdateRequest buildPartial() {
      com.alterra.deoxys.stub.UpdateRequest result = new com.alterra.deoxys.stub.UpdateRequest(this);
      result.api_ = api_;
      if (toDoBuilder_ == null) {
        result.toDo_ = toDo_;
      } else {
        result.toDo_ = toDoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alterra.deoxys.stub.UpdateRequest) {
        return mergeFrom((com.alterra.deoxys.stub.UpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alterra.deoxys.stub.UpdateRequest other) {
      if (other == com.alterra.deoxys.stub.UpdateRequest.getDefaultInstance()) return this;
      if (!other.getApi().isEmpty()) {
        api_ = other.api_;
        onChanged();
      }
      if (other.hasToDo()) {
        mergeToDo(other.getToDo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alterra.deoxys.stub.UpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alterra.deoxys.stub.UpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object api_ = "";
    /**
     * <pre>
     * API versioning: it is my best practice to specify version explicitly
     * </pre>
     *
     * <code>string api = 1;</code>
     */
    public java.lang.String getApi() {
      java.lang.Object ref = api_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        api_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * API versioning: it is my best practice to specify version explicitly
     * </pre>
     *
     * <code>string api = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApiBytes() {
      java.lang.Object ref = api_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        api_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * API versioning: it is my best practice to specify version explicitly
     * </pre>
     *
     * <code>string api = 1;</code>
     */
    public Builder setApi(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      api_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * API versioning: it is my best practice to specify version explicitly
     * </pre>
     *
     * <code>string api = 1;</code>
     */
    public Builder clearApi() {
      
      api_ = getDefaultInstance().getApi();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * API versioning: it is my best practice to specify version explicitly
     * </pre>
     *
     * <code>string api = 1;</code>
     */
    public Builder setApiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      api_ = value;
      onChanged();
      return this;
    }

    private com.alterra.deoxys.stub.ToDo toDo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alterra.deoxys.stub.ToDo, com.alterra.deoxys.stub.ToDo.Builder, com.alterra.deoxys.stub.ToDoOrBuilder> toDoBuilder_;
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public boolean hasToDo() {
      return toDoBuilder_ != null || toDo_ != null;
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public com.alterra.deoxys.stub.ToDo getToDo() {
      if (toDoBuilder_ == null) {
        return toDo_ == null ? com.alterra.deoxys.stub.ToDo.getDefaultInstance() : toDo_;
      } else {
        return toDoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public Builder setToDo(com.alterra.deoxys.stub.ToDo value) {
      if (toDoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toDo_ = value;
        onChanged();
      } else {
        toDoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public Builder setToDo(
        com.alterra.deoxys.stub.ToDo.Builder builderForValue) {
      if (toDoBuilder_ == null) {
        toDo_ = builderForValue.build();
        onChanged();
      } else {
        toDoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public Builder mergeToDo(com.alterra.deoxys.stub.ToDo value) {
      if (toDoBuilder_ == null) {
        if (toDo_ != null) {
          toDo_ =
            com.alterra.deoxys.stub.ToDo.newBuilder(toDo_).mergeFrom(value).buildPartial();
        } else {
          toDo_ = value;
        }
        onChanged();
      } else {
        toDoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public Builder clearToDo() {
      if (toDoBuilder_ == null) {
        toDo_ = null;
        onChanged();
      } else {
        toDo_ = null;
        toDoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public com.alterra.deoxys.stub.ToDo.Builder getToDoBuilder() {
      
      onChanged();
      return getToDoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    public com.alterra.deoxys.stub.ToDoOrBuilder getToDoOrBuilder() {
      if (toDoBuilder_ != null) {
        return toDoBuilder_.getMessageOrBuilder();
      } else {
        return toDo_ == null ?
            com.alterra.deoxys.stub.ToDo.getDefaultInstance() : toDo_;
      }
    }
    /**
     * <pre>
     * Task entity to update
     * </pre>
     *
     * <code>.v1.ToDo toDo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.alterra.deoxys.stub.ToDo, com.alterra.deoxys.stub.ToDo.Builder, com.alterra.deoxys.stub.ToDoOrBuilder> 
        getToDoFieldBuilder() {
      if (toDoBuilder_ == null) {
        toDoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.alterra.deoxys.stub.ToDo, com.alterra.deoxys.stub.ToDo.Builder, com.alterra.deoxys.stub.ToDoOrBuilder>(
                getToDo(),
                getParentForChildren(),
                isClean());
        toDo_ = null;
      }
      return toDoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v1.UpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:v1.UpdateRequest)
  private static final com.alterra.deoxys.stub.UpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alterra.deoxys.stub.UpdateRequest();
  }

  public static com.alterra.deoxys.stub.UpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateRequest>() {
    @java.lang.Override
    public UpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alterra.deoxys.stub.UpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

